# Use root/example as user/password credentials
services:
  db:
    image: mysql
    container_name: dev-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: development
    volumes:
      - dev-mysql:/var/lib/mysql
volumes:
  dev-mysql:
